#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XMart.Droid.Resource", IsApplication=true)]

namespace XMart.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int back_gray = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int box = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int cart = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int cart_gray = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int category = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int category_gray = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int circle = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int comment = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int default_female = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int default_male = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int home = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int home_gray = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int login_bg = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int me = 2130837518;
			
			// aapt resource value: 0x7F020010
			public const int message = 2130837520;
			
			// aapt resource value: 0x7F02000F
			public const int me_gray = 2130837519;
			
			// aapt resource value: 0x7F020011
			public const int navi_back = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int order_red = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int pay = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int service = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int service2 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int splashscreen = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int start = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int xmart_logo = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int xmart_logo2 = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int xmart = 2131034115;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int Theme_Splash = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
